//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.24 at 08:50:20 PM NZST 
//


package com.rabidgremlin.fddreport.bindings;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.rabidgremlin.fddreport.bindings package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.rabidgremlin.fddreport.bindings
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Project }
     * 
     */
    public Project createProject() {
        return new Project();
    }

    /**
     * Create an instance of {@link Project.FeatureSets.FeatureSet }
     * 
     */
    public Project.FeatureSets.FeatureSet createProjectFeatureSetsFeatureSet() {
        return new Project.FeatureSets.FeatureSet();
    }

    /**
     * Create an instance of {@link Project.Features.Feature }
     * 
     */
    public Project.Features.Feature createProjectFeaturesFeature() {
        return new Project.Features.Feature();
    }

    /**
     * Create an instance of {@link Project.FeatureSets }
     * 
     */
    public Project.FeatureSets createProjectFeatureSets() {
        return new Project.FeatureSets();
    }

    /**
     * Create an instance of {@link Project.Features }
     * 
     */
    public Project.Features createProjectFeatures() {
        return new Project.Features();
    }

}
