//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.24 at 08:50:20 PM NZST 
//


package com.rabidgremlin.fddreport.bindings;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FeatureSets">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="FeatureSet">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="FeatureSetId" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *                           &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Features">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="Feature">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="FeatureSet" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *                           &lt;attribute name="DomainWalkthroughPlanned" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                           &lt;attribute name="DomainWalkthroughActual" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                           &lt;attribute name="DesignPlanned" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                           &lt;attribute name="DesignActual" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                           &lt;attribute name="DesignReviewPlanned" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                           &lt;attribute name="DesignReviewActual" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                           &lt;attribute name="CodePlanned" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                           &lt;attribute name="CodeActual" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                           &lt;attribute name="CodeReviewPlanned" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                           &lt;attribute name="CodeReviewActual" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                           &lt;attribute name="PromoteToBuildPlanned" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                           &lt;attribute name="PromoteToBuildActual" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="ProjectName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="StartDate" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "featureSets",
    "features"
})
@XmlRootElement(name = "Project")
public class Project {

    @XmlElement(name = "FeatureSets", required = true)
    protected Project.FeatureSets featureSets;
    @XmlElement(name = "Features", required = true)
    protected Project.Features features;
    @XmlAttribute(name = "ProjectName", required = true)
    protected String projectName;
    @XmlAttribute(name = "StartDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar startDate;

    /**
     * Gets the value of the featureSets property.
     * 
     * @return
     *     possible object is
     *     {@link Project.FeatureSets }
     *     
     */
    public Project.FeatureSets getFeatureSets() {
        return featureSets;
    }

    /**
     * Sets the value of the featureSets property.
     * 
     * @param value
     *     allowed object is
     *     {@link Project.FeatureSets }
     *     
     */
    public void setFeatureSets(Project.FeatureSets value) {
        this.featureSets = value;
    }

    /**
     * Gets the value of the features property.
     * 
     * @return
     *     possible object is
     *     {@link Project.Features }
     *     
     */
    public Project.Features getFeatures() {
        return features;
    }

    /**
     * Sets the value of the features property.
     * 
     * @param value
     *     allowed object is
     *     {@link Project.Features }
     *     
     */
    public void setFeatures(Project.Features value) {
        this.features = value;
    }

    /**
     * Gets the value of the projectName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * Sets the value of the projectName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectName(String value) {
        this.projectName = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="FeatureSet">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="FeatureSetId" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
     *                 &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "featureSet"
    })
    public static class FeatureSets {

        @XmlElement(name = "FeatureSet", required = true)
        protected List<Project.FeatureSets.FeatureSet> featureSet;

        /**
         * Gets the value of the featureSet property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the featureSet property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFeatureSet().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Project.FeatureSets.FeatureSet }
         * 
         * 
         */
        public List<Project.FeatureSets.FeatureSet> getFeatureSet() {
            if (featureSet == null) {
                featureSet = new ArrayList<Project.FeatureSets.FeatureSet>();
            }
            return this.featureSet;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="FeatureSetId" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
         *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class FeatureSet {

            @XmlAttribute(name = "FeatureSetId", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlID
            @XmlSchemaType(name = "ID")
            protected String featureSetId;
            @XmlAttribute(name = "Name", required = true)
            protected String name;

            /**
             * Gets the value of the featureSetId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFeatureSetId() {
                return featureSetId;
            }

            /**
             * Sets the value of the featureSetId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFeatureSetId(String value) {
                this.featureSetId = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="Feature">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="FeatureSet" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
     *                 &lt;attribute name="DomainWalkthroughPlanned" type="{http://www.w3.org/2001/XMLSchema}date" />
     *                 &lt;attribute name="DomainWalkthroughActual" type="{http://www.w3.org/2001/XMLSchema}date" />
     *                 &lt;attribute name="DesignPlanned" type="{http://www.w3.org/2001/XMLSchema}date" />
     *                 &lt;attribute name="DesignActual" type="{http://www.w3.org/2001/XMLSchema}date" />
     *                 &lt;attribute name="DesignReviewPlanned" type="{http://www.w3.org/2001/XMLSchema}date" />
     *                 &lt;attribute name="DesignReviewActual" type="{http://www.w3.org/2001/XMLSchema}date" />
     *                 &lt;attribute name="CodePlanned" type="{http://www.w3.org/2001/XMLSchema}date" />
     *                 &lt;attribute name="CodeActual" type="{http://www.w3.org/2001/XMLSchema}date" />
     *                 &lt;attribute name="CodeReviewPlanned" type="{http://www.w3.org/2001/XMLSchema}date" />
     *                 &lt;attribute name="CodeReviewActual" type="{http://www.w3.org/2001/XMLSchema}date" />
     *                 &lt;attribute name="PromoteToBuildPlanned" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
     *                 &lt;attribute name="PromoteToBuildActual" type="{http://www.w3.org/2001/XMLSchema}date" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "feature"
    })
    public static class Features {

        @XmlElement(name = "Feature", required = true)
        protected List<Project.Features.Feature> feature;

        /**
         * Gets the value of the feature property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the feature property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFeature().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Project.Features.Feature }
         * 
         * 
         */
        public List<Project.Features.Feature> getFeature() {
            if (feature == null) {
                feature = new ArrayList<Project.Features.Feature>();
            }
            return this.feature;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="FeatureSet" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
         *       &lt;attribute name="DomainWalkthroughPlanned" type="{http://www.w3.org/2001/XMLSchema}date" />
         *       &lt;attribute name="DomainWalkthroughActual" type="{http://www.w3.org/2001/XMLSchema}date" />
         *       &lt;attribute name="DesignPlanned" type="{http://www.w3.org/2001/XMLSchema}date" />
         *       &lt;attribute name="DesignActual" type="{http://www.w3.org/2001/XMLSchema}date" />
         *       &lt;attribute name="DesignReviewPlanned" type="{http://www.w3.org/2001/XMLSchema}date" />
         *       &lt;attribute name="DesignReviewActual" type="{http://www.w3.org/2001/XMLSchema}date" />
         *       &lt;attribute name="CodePlanned" type="{http://www.w3.org/2001/XMLSchema}date" />
         *       &lt;attribute name="CodeActual" type="{http://www.w3.org/2001/XMLSchema}date" />
         *       &lt;attribute name="CodeReviewPlanned" type="{http://www.w3.org/2001/XMLSchema}date" />
         *       &lt;attribute name="CodeReviewActual" type="{http://www.w3.org/2001/XMLSchema}date" />
         *       &lt;attribute name="PromoteToBuildPlanned" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
         *       &lt;attribute name="PromoteToBuildActual" type="{http://www.w3.org/2001/XMLSchema}date" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Feature {

            @XmlAttribute(name = "Name", required = true)
            protected String name;
            @XmlAttribute(name = "FeatureSet", required = true)
            @XmlIDREF
            @XmlSchemaType(name = "IDREF")
            protected Object featureSet;
            @XmlAttribute(name = "DomainWalkthroughPlanned")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar domainWalkthroughPlanned;
            @XmlAttribute(name = "DomainWalkthroughActual")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar domainWalkthroughActual;
            @XmlAttribute(name = "DesignPlanned")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar designPlanned;
            @XmlAttribute(name = "DesignActual")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar designActual;
            @XmlAttribute(name = "DesignReviewPlanned")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar designReviewPlanned;
            @XmlAttribute(name = "DesignReviewActual")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar designReviewActual;
            @XmlAttribute(name = "CodePlanned")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar codePlanned;
            @XmlAttribute(name = "CodeActual")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar codeActual;
            @XmlAttribute(name = "CodeReviewPlanned")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar codeReviewPlanned;
            @XmlAttribute(name = "CodeReviewActual")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar codeReviewActual;
            @XmlAttribute(name = "PromoteToBuildPlanned", required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar promoteToBuildPlanned;
            @XmlAttribute(name = "PromoteToBuildActual")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar promoteToBuildActual;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the featureSet property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getFeatureSet() {
                return featureSet;
            }

            /**
             * Sets the value of the featureSet property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setFeatureSet(Object value) {
                this.featureSet = value;
            }

            /**
             * Gets the value of the domainWalkthroughPlanned property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getDomainWalkthroughPlanned() {
                return domainWalkthroughPlanned;
            }

            /**
             * Sets the value of the domainWalkthroughPlanned property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setDomainWalkthroughPlanned(XMLGregorianCalendar value) {
                this.domainWalkthroughPlanned = value;
            }

            /**
             * Gets the value of the domainWalkthroughActual property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getDomainWalkthroughActual() {
                return domainWalkthroughActual;
            }

            /**
             * Sets the value of the domainWalkthroughActual property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setDomainWalkthroughActual(XMLGregorianCalendar value) {
                this.domainWalkthroughActual = value;
            }

            /**
             * Gets the value of the designPlanned property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getDesignPlanned() {
                return designPlanned;
            }

            /**
             * Sets the value of the designPlanned property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setDesignPlanned(XMLGregorianCalendar value) {
                this.designPlanned = value;
            }

            /**
             * Gets the value of the designActual property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getDesignActual() {
                return designActual;
            }

            /**
             * Sets the value of the designActual property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setDesignActual(XMLGregorianCalendar value) {
                this.designActual = value;
            }

            /**
             * Gets the value of the designReviewPlanned property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getDesignReviewPlanned() {
                return designReviewPlanned;
            }

            /**
             * Sets the value of the designReviewPlanned property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setDesignReviewPlanned(XMLGregorianCalendar value) {
                this.designReviewPlanned = value;
            }

            /**
             * Gets the value of the designReviewActual property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getDesignReviewActual() {
                return designReviewActual;
            }

            /**
             * Sets the value of the designReviewActual property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setDesignReviewActual(XMLGregorianCalendar value) {
                this.designReviewActual = value;
            }

            /**
             * Gets the value of the codePlanned property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getCodePlanned() {
                return codePlanned;
            }

            /**
             * Sets the value of the codePlanned property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setCodePlanned(XMLGregorianCalendar value) {
                this.codePlanned = value;
            }

            /**
             * Gets the value of the codeActual property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getCodeActual() {
                return codeActual;
            }

            /**
             * Sets the value of the codeActual property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setCodeActual(XMLGregorianCalendar value) {
                this.codeActual = value;
            }

            /**
             * Gets the value of the codeReviewPlanned property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getCodeReviewPlanned() {
                return codeReviewPlanned;
            }

            /**
             * Sets the value of the codeReviewPlanned property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setCodeReviewPlanned(XMLGregorianCalendar value) {
                this.codeReviewPlanned = value;
            }

            /**
             * Gets the value of the codeReviewActual property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getCodeReviewActual() {
                return codeReviewActual;
            }

            /**
             * Sets the value of the codeReviewActual property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setCodeReviewActual(XMLGregorianCalendar value) {
                this.codeReviewActual = value;
            }

            /**
             * Gets the value of the promoteToBuildPlanned property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getPromoteToBuildPlanned() {
                return promoteToBuildPlanned;
            }

            /**
             * Sets the value of the promoteToBuildPlanned property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setPromoteToBuildPlanned(XMLGregorianCalendar value) {
                this.promoteToBuildPlanned = value;
            }

            /**
             * Gets the value of the promoteToBuildActual property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getPromoteToBuildActual() {
                return promoteToBuildActual;
            }

            /**
             * Sets the value of the promoteToBuildActual property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setPromoteToBuildActual(XMLGregorianCalendar value) {
                this.promoteToBuildActual = value;
            }

        }

    }

}
